name: Release
description: Publishes a package to NPM and creates and pushes a new tag

on:
  workflow_call:
    inputs:
      package-path:
        description: The path to the package directory
        required: true
        type: string
    secrets:
      npm-token:
        description: NPM access token to publish the package
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get local package information
        id: local
        uses: aspithost/actions/npm/get-local-package-information@v0
        with:
          working-directory: ${{ inputs.package-path }}

      - name: Get remote package version
        id: remote
        uses: aspithost/actions/npm/get-remote-package-version@v0
        with:
          package-name: ${{ steps.local.outputs.name }}

      - name: Setup Node
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org

      - name: Publish package
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: aspithost/actions/npm/publish@v0
        with:
          package-path: ${{ inputs.package-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Create and push tag
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: aspithost/actions/git/create-and-push-tag@v0
        with:
          package-name: ${{ steps.local.outputs.name }}
          package-version: ${{ steps.local.outputs.version }}
